<?php
/**
 * @file
 * Prepare testing environment on DigitalOcean.
 * Spin Up VPS to process tests and destroy after.
 */

/**
 * Implements hook_config_info().
 */
function zenci_google_ce_config_info() {
  $prefixes['zenci_google_ce.settings'] = array(
    'label' => t('ZenCI GoogleComputeEngine API settings'),
    'group' => t('Configuration'),
  );
  return $prefixes;
}

/**
 * Implements hook_permission().
 */
function zenci_google_ce_permission() {
  return array(
    'test job view' => array(
      'title' => t('Access job results'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function zenci_google_ce_menu() {
  $items = array();

  $items['admin/config/system/google_ce'] = array(
    'title' => 'GoogleComputeEngine settings',
    'description' => 'GoogleComputeEngine settings.',
    'page callback' => 'zenci_google_ce_templates',
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/system/google_ce/list'] = array(
    'title' => 'GoogleComputeEngine Templates',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  // Admin settings page.
  $items['admin/config/system/google_ce/settings'] = array(
    'title' => 'GoogleComputeEngine settings',
    'description' => 'GoogleComputeEngine settings.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('zenci_google_ce_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
  );

  $items['admin/config/system/google_ce/template_add'] = array(
    'title' => 'Add template',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('zenci_google_ce_template', 4),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/system/google_ce/instance_add'] = array(
    'title' => 'Add instance',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('zenci_google_ce_instance', 4),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_CALLBACK,
  );

  $items['admin/config/system/google_ce/instance_del'] = array(
    'title' => 'Delete instance',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('zenci_google_ce_instance_del', 4),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_CALLBACK,
  );


  $items['admin/config/system/google_ce/%/delete'] = array(
    'title' => 'Remove template',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('zenci_google_ce_template_remove', 4),
    'access callback' => 'user_access',
    'access arguments' => array('administer site configuration'),
    'file' => 'zenci_google_ce.admin.inc',
    'type' => MENU_CALLBACK,
  );
  

  $items['zenci_joblist'] = array(
    'title' => 'ZenCI tests results',
    'description' => 'View result of tests.',
    'page callback' => 'zenci_google_ce_job_list',
    'access callback' => 'user_access',
    'access arguments' => array('test job view'),
    'file' => 'zenci_google_ce.pages.inc',
    'type' => MENU_NORMAL_ITEM,  
  );  

  return $items;
}

/**
 * Implements hook_zenci_webhook().
 */
function zenci_google_ce_zenci_webhook($method, $data) {
  switch ($method) {
    case 'config':
      /** ZenCI config reguest from ZenCI server.
       *
       * @param $data array
       *   - owner: GitHub organisation or user.
       *   - repo: GitHub repository name.
       *   - branch: repository branch that is going to be deployed.
       *
       * @return
       *   array with 'config' value where gitlc.yml file is base64 encoded.
       */
       
      // Create VPS and pass back deploy and testing structure.
      
      $config_filepath = backdrop_get_path('module', 'zenci_google_ce') . '/gitlc.yml';

      if ($config = file_get_contents($config_filepath)) {
        return array(
          'config' => base64_encode($config),
        );
      }
      break;
    case 'google_ce_before':
      /** ZenCI before test request from ZenCI server.
       *
       * @param $data array
       *   - config: current config structure. Usefull if provided by .gitlc.yml file in GitHub Repository.
       *     - env_vars: Enviorment values set by script or Gitlc.
       *   - repo_name: GitHub repository name.
       *   - repo_owner: GitHub repository owner.
       *   - branch: repository branch that is going to be deployed.
       *   - pull_request: PR number or FALSE.
       *   - action: create,push,opened,synchronize.
       *   - test: test name.
       *
       * @return
       *   array with 'env_vars'. All enviotment variables will be available via ENV in scripts.
       */
       
       switch($data['action']){
         case 'create':
         case 'push':
         case 'opened':
         case 'synchronize':
           // create VPS
           $prefix = '';
           if($data['pull_request']){
             $prefix .= $data['pull_request'] . "-";
           }
           $name = $data['branch'] . "-" . $data['repo_name'] . "-" . $data['repo_owner'];
           if(isset($data['sha'])){
             $name = $name . "-" . substr($data['sha'], 0, 6);
           }
           $name = strtolower($name);
           $instance = zenci_google_ce_create_instance($name, $data['test']);
           
           
           $answer = array();
           $answer['server'] = $instance['ip'];
           return $answer;
         break;         
       }
      break;
    case 'google_ce_after':
      /** ZenCI before test request from ZenCI server.
       *
       * @param $data array
       *   - config: current config structure. Usefull if provided by .gitlc.yml file in GitHub Repository.
       *     - env_vars: Enviorment values set by script or Gitlc.
       *   - repo_name: GitHub repository name.
       *   - repo_owner: GitHub repository owner.
       *   - branch: repository branch that is going to be deployed.
       *   - pull_request: PR number or FALSE.
       *   - action: create,push,.
       *
       * @return
       *   array with 'env_vars'. All enviotment variables will be available via ENV in scripts.
       */
       
       switch($data['action']){
         case 'create':
         case 'push':
         case 'opened':
         case 'synchronize':
           // destroy VPS
           $prefix = '';
           if($data['pull_request']){
             $prefix .= $data['pull_request'] . "-";
           }
           $name = $data['branch'] . "-" . $data['repo_name'] . "-" . $data['repo_owner'];
           if(isset($data['sha'])){
             $name = $name . "-" . substr($data['sha'], 0, 6);
           }
           $name = strtolower($name);
           $instance = db_select('zenci_google_ce_instances', 'gh')
              ->fields('gh')
              ->condition('name', $name)
              ->execute()
              ->fetchObject();
            if($instance){
             zenci_google_ce_delete_instance($instance);
            }
           
           
         break;         
       }
      break;
      
  }
  return $data;
}

function zenci_google_ce_get_value($env_vars, $variable) {
  if (isset($env_vars[$variable])) {
    return $env_vars[$variable];
  }
  FALSE;
}

function zenci_google_ce_get_class() {
  module_load_include('inc', 'zenci_google_ce', 'zenci_google_ce.class');

  $private_key = zenci_google_ce_get_private_key();
  $project_id = zenci_google_ce_get_project_id();    

  $GoogleComputeEngineAPI = new GoogleComputeEngineAPI();
//  $GoogleComputeEngineAPI->setProjectID($project_id);
//  $GoogleComputeEngineAPI->setPrivateKey($private_key);
  
  return $GoogleComputeEngineAPI;
}

function zenci_google_ce_get_private_key() {
  $config = config('zenci_google_ce.settings');
  
  $private_key = settings_get('zenci_google_ce_private_key');

  if (empty($private_key)) {
    $private_key = $config->get('private_key');  
  }

  return $private_key;
}

function zenci_google_ce_get_project_id() {
  $config = config('zenci_google_ce.settings');
  
  $project_id = settings_get('zenci_google_ce_project_id');

  if (empty($project_id)) {
    $project_id = $config->get('project_id');  
  }

  return $project_id;
}

function zenci_google_ce_create_instance($name, $template_name){
  $template = db_select('zenci_google_ce_templates', 'gh')
    ->fields('gh')
    ->condition('name', $template_name)
    ->execute()
    ->fetchObject();
    
  watchdog('zenci_google_ce', ' Create instance !name !template_name', array('!name' => $name, '!template_name' => $template_name));
  
  $GoogleComputeEngineAPI = zenci_google_ce_get_class();

  $instance = $GoogleComputeEngineAPI->createInstance($name, $template);  
  
  if($instance){
    $record = array(
      'name' => $name,
      'created' => time(), // Here we need to parse : [creationTimestamp] => 2016-05-13T11:49:54.890-07:00
      'owner' => 'owner', //repo owner.
      'repo' => 'repo', // repo name.
      'branch' => 'branch', //branch name.
      'pr' => 0, //pr number
      'template' => $template_name,
      'results' => 'some data here', 
      'zone' => $instance['zone_name'],
      'ip' => $instance['ip_address']
    );
    if(FALSE !== backdrop_write_record('zenci_google_ce_instances', $record)){
      return $record;
    }
  } else {
    watchdog('zenci_google_ce', 'Create false : ' . print_r($GoogleComputeEngineAPI->testingGetHeaders(),true));
  }
  return FALSE;
}

function zenci_google_ce_delete_instance($instance){
  watchdog('zenci_google_ce', ' Delete instance !name', array('!name' => $instance->name));

  $GoogleComputeEngineAPI = zenci_google_ce_get_class();
  return $GoogleComputeEngineAPI->deleteInstance($instance->zone, $instance->name);
}
